### PR TITLE
this.* to spread operator

### PR DESCRIPTION
**Pull request by angrymouse**

### CODE REVIEW

**Comment by develop331** [comment]
Question, how did you come about disc.script seeing as it's heavily in WIP

**Review by develop331 — APPROVED** [review]

**Comment by angrymouse** [comment]
npm recently updated packages xD

**Comment by develop331** [comment]
This broke the Guild object

**Comment by develop331** [comment]
Turns out JS classes don't like using the spread operator for this.* looping. Am now resolving issues and rolling back versions.

**Comment by develop331** [comment]
All bugs to do with #1 should now be fixed. Locking PR. For any other issues, create a thread in issues.

**Pull request merged**
